services:
  mysql:
    image: mysql:8.4.8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: wallet-provider
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./wallet-provider-service/src/test/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql:RO
  adminer:
    image: adminer:5.4.2-standalone
    restart: unless-stopped
    ports:
      - "9000:8080"